# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2000a8548f8d39eec968ed161eea292522c400247c5696c0d38de2992dc16eaab9ca43011883b3918584c33eb8f52e3ab58b6b2777f24d3272de84e495a946cd

test:
  secret_key_base: c4e5c35d0dbff4576c49d9d04b3d0e46b5152b31a4ad797d0bec84430d443c174c7cceafc50d03dd6b5be1edd86cf7a5b475550e01b155d20104d79753c1fb2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
